{
 "title": "Azure Functions",
 "description": "Azure Functions Monitoring Dashboard that indicates eventHub metrics from Azure",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "ResourceGroup", "label": "Resource Group", "query": "ResourceGroups()" },
   {
    "name": "ResourceName",
    "label": "Azure Function Name",
    "query": "ResourceNames($ResourceGroup,microsoft.web/sites)"
   }
  ]
 },
 "panels": [
  {
   "title": "Function Execution Units",
   "type": "timeseries",
   "description": "Function execution units shows a combination of execution time and memory usage, which makes it a problematic metric for understanding memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FunctionExecutionUnits",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Working Memory Set",
   "type": "timeseries",
   "description": "The working set of the function shows the set of pages in the virtual address space of the process that are currently resident in physical memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Function Execution Count",
   "type": "timeseries",
   "description": "This counter shows the number of the function execution.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FunctionExecutionCount",
      "metricNamespace": "microsoft.web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}